[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "2oy6dWTL4PB4JTBWbfwRphjQjYXnSx7CLpicAXJCX2pV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
